### ISSUE TITLE
Design: Support for multiple WebAuthn devices for each user

### ISSUE THREAD

**Issue by smkent** [authelia/authelia#4366]
### Description

Desired user scenarios:

* Users can add more than one WebAuthn device to their account ([listed on Authelia's WebAuthn roadmap](https://www.authelia.com/roadmap/active/webauthn/#multi-device-registration))
  * Registered device name can be provided by the user during device registration
* Users can manage their existing WebAuthn devices within their account ([listed on Authelia's Dashboard / Control Panel roadmap](https://www.authelia.com/roadmap/active/dashboard-control-panel/#initial-implementation))
  * View information about registered device(s)
  * Rename existing device(s)
  * Add additional device(s)
  * Delete existing device(s)

### Use Case

It's common and recommended for users with hardware security tokens (ex. Yubikeys) to have more than one. As an example, I have a backup Yubikey in case my main key gets lost. Each of my Yubikeys are configured in my accounts where I use them for 2-factor authentication. Hardware security tokens are usable via the WebAuthn protocol, which Authelia already uses and supports.

Sites which support hardware security tokens for 2-factor authentication generally support this use case. Examples include Google, Dropbox, and GitHub. 

This feature was requested in https://github.com/authelia/authelia/issues/275.

### Details

For reference, this is the current WebAuthn device registration flow:

1. On the login frame (at either the `OneFactor` or `TwoFactor` authentication levels), the user clicks the "Lost your device?" link
![registration-flow-link](https://user-images.githubusercontent.com/2831985/201496556-947cbf09-dbc6-4794-af70-5c3656315735.png)
2. Authelia generates a token, encoded as JWT, and sends the user an email containing a link with the JWT token
3. User clicks the link in their email
4. Authelia retrieves the token from the URI, decodes and verifies the JWT, and [performs the WebAuthn attestation ceremony](https://github.com/authelia/authelia/blob/c7a668c897cbda49d858a19e40705dca88e1ca3e/web/src/views/DeviceRegistration/RegisterWebauthn.tsx#L35).
5. On successful WebAuthn device attestation, the new device info is stored in the Authelia database. [Currently the device registration is hardcoded with a description of `Primary`](https://github.com/authelia/authelia/blob/c7a668c897cbda49d858a19e40705dca88e1ca3e/internal/handlers/handler_register_webauthn.go#L137). If an existing device was registered, it is overwritten.
6. On WebAuthn device registration success, the user is redirected back to the login page (which then re-prompts for 2FA authentication with the new device).

#### Proposed changes: Users can add more than one WebAuthn device to their account

* As mentioned on Authelia's [WebAuthn roadmap](https://www.authelia.com/roadmap/active/webauthn/#multi-device-registration), the storage backend has existing support for multiple devices. Devices are overwritten on re-registration simply due to the hardcoded name (referred to in the backend as "description") `Primary` which is used for all devices. The hardcoded device name should be removed so it can be provided to the backend via the API as in https://github.com/authelia/authelia/pull/4363.

* Support entry of a user-provided device name as part of the WebAuthn device registration flow. This can then be provided to the backend on registration via the previously mentioned API change.
  * The user should be prevented from reusing the name of existing device within their account by both the UI and backend

#### Proposed changes: Users can manage their existing WebAuthn devices within their account

* New UI is needed for device management. From the roadmap and discussions on Discord, the desired feature is an extensible user account settings UI. Although the UI may only support WebAuthn device management initially, this UI would later provide options for management of other 2FA options and other unrelated settings (such as Authelia service configuration options, perhaps).
  * Some existing features work around a settings UI is present in the [`feat-settings-ui` branch](https://github.com/authelia/authelia/tree/feat-settings-ui). The UI in this branch currently looks like this:
  
![feat-settings-ui](https://user-images.githubusercontent.com/2831985/201496602-a4a765f9-6991-4642-99e8-8fc5bcc25305.png)

 
* WebAuthn settings UI should display information about registered devices:
  * User-entered device name ("description" in the backend)
  * Additional details such as registered date, and last used date. These values are already stored in the database.
  * No API endpoint currently exists for retrieving configured WebAuthn device information for a user. A new API endpoint is needed. (A new endpoint is present in the [`feat-settings-ui` branch](https://github.com/authelia/authelia/tree/feat-settings-ui).)

* WebAuthn settings UI should allow registration of multiple devices. Some options:
  1. Reuse existing registration flow. Without additional changes, re-launching the flow will send the user another email with a link+token. Opening this page will start the WebAuthn device attestation/registration flow. Pros: Smallest code change. Cons: Cumbersome for the user, as it requires an email round-trip for each new added device.
  2. Reuse existing registration flow, without requiring email verification when already logged in at the `TwoFactor` level. Pros: Still a smaller code change. Less cumbersome for the user. No expected security impact as the user already had to verify their email to register/log in with 2FA in the first place. Cons: Redirection to existing flow may be jarring for users.
  3. Reuse existing registration flow in a popup modal over the new settings UI, without requiring email verification when already logged in at the `TwoFactor` level. Pros: Most intuitive flow for the user. Modal popup makes it more obvious the registration function operates within the settings UI space. No expected security impact as the user already had to verify their email to register/log in with 2FA in the first place. Cons: Largest code change.
  * **Note**: Skipping email verification when logged in at the `TwoFactor` level could be accomplished by simply succeeding the [identity verification middleware](https://github.com/authelia/authelia/blob/c7a668c897cbda49d858a19e40705dca88e1ca3e/internal/middlewares/identity_verification.go) if the user's auth level is `TwoFactor`. I sketched this out here: https://github.com/smkent/authelia/pull/1

* WebAuthn settings UI should allow rename of multiple devices.
  * A new API endpoint is needed for modifying a WebAuthn device.

* WebAuthn settings UI should allow deletion of multiple devices.
  * A new API endpoint is needed for deleting a WebAuthn device.
  * When all WebAuthn devices are deleted, my preferred option is to:
    1. Do nothing. The user will remain logged in at the `TwoFactor` level within their current session. Logging in again will automatically restart the 2FA device registration prompt if no other 2FA methods are enabled. Pros: Less disruptive flow for the user. User can delete their last device and (re-)add a device in the settings UI without their session ending.

#### Additional considerations

* Email-based identity verification may be reworked via https://github.com/authelia/authelia/issues/3801, which would replace the JWT token with a randomly generated one time password. This may affect some of the proposed feature implementation above.

### Implementation steps

* Remove hardcoded `Primary` device name for registered WebAuthn devices: https://github.com/authelia/authelia/pull/4363
* Add device name prompt to WebAuthn device registration flow UI, and pass the entered name on registration in the API. Require a unique name for each of the user's devices, by indicating if the requested name is in use [in the `/api/secondfactor/webauthn/attestation` response](https://github.com/authelia/authelia/blob/c7a668c897cbda49d858a19e40705dca88e1ca3e/internal/handlers/handler_register_webauthn.go#L85)
* ~~Add an endpoint to retrieve a user's WebAuthn devices information~~ [(implemented within `feat-settings-ui`)](https://github.com/authelia/authelia/blob/bbc9e6422ed197557447cb11bf64880f52c24735/internal/handlers/handler_webauthn_devices.go#L7)
* Create new UI for WebAuthn device management (as an extensible Settings UI) (partially implemented within `feat-settings-ui`)
* Support WebAuthn device registration within the new settings UI
  * Skip identity verification when registering a new WebAuthn device if the user is already logged in with 2FA (WIP code https://github.com/smkent/authelia/pull/1)
  * Organize existing WebAuthn device registration flow into a React component
  * Provide option to launch WebAuthn device registration flow from the new settings UI
* Support WebAuthn device rename within the new settings UI
  * Add API endpoint for setting the name of an existing WebAuthn device
  * Implement device rename in the settings UI using the above-mentioned endpoint
* Support WebAuthn device deletion within the new settings UI
  * Add API endpoint for deleting an existing WebAuthn device
  * Implement device deletion in the settings UI using the above-mentioned endpoint

#### Feature work follow-ups

These todo items follow the implementation of the major design features in this issue.

- Webauthn UI improvements:
  - [x] Implement Webauthn device rename UI https://github.com/authelia/authelia/pull/4427
  - [x] Confirm before deleting Webauthn devices https://github.com/authelia/authelia/pull/4426
  - [x] Use more compact display or alternate presentation method for Webauthn devices table https://github.com/authelia/authelia/pull/4435
    - Consider Webauthn / security key management UI designs in other apps for inspiration
    - Perhaps keys should be tiles instead of table rows?
    - Choose UI element(s) that work well with expandable / extended information
  - [x] Open question: Should edit / delete actions show progress / failure or be optimistic?
    - #4426 and #4427 implement a loading spinner while edit/delete are in progress
  - [x] Show a loading block in place of the devices list while the devices list is still loading https://github.com/authelia/authelia/pull/4406
  - [x] Indicate in the UI when no Webauthn devices are registered https://github.com/authelia/authelia/pull/4405
- General UI improvements:
  - [x] Add element to close UI and return to login flow / landing page
  - ~~Open question: Should the left settings nav bar be collapsible?~~ (IMO this is feature creep for now)
- Naming and text conventions
  - [x] Rename the settings UI `AppBar` text from "Settings" to something more general (perhaps with Authelia branding) https://github.com/authelia/authelia/pull/4454
  - [ ] Use consistent naming for Webauthn devices https://github.com/authelia/authelia/pull/4453
    - The current UI refers to these as Webauthn devices in some places and security keys in others. We should choose and implement consistent naming for this feature. (TOTP / "One-Time Password" merits similar attention.)
    - [From discussion on Discord](https://discord.com/channels/707844280412012608/804943261265297408/1045214230464446524), we'll go with "Security Key (Webauthn)."
- Testing
  - [ ] Ensure new features are covered by tests

#### Additional todos / visual nits

- [x] Format added and last used timestamps in a more friendly format. Currently raw UTC timestamps are shown.
  - Do we need additional package(s) for this or is there native date formatting support?
- [x] Change settings UI "Close" button color from green to something more sensible
- [x] Remove currently unused "Overview" tab from the left menu bar in the settings view
- [x] (Optional -- is this needed?) Remove the gear icon settings page button from the login flow. The settings page is accessible via the security key device registration and management links in the login frame.

### Future settings UI-related feature work

These are additional brainstorming and should be ticketed separately.

- Move TOTP management and enrollment flow into the settings UI
- Move Duo management and enrollment flow into the settings UI
- Indicate which 2FA methods are enabled / default in the settings UI
- If the new settings UI will serve as the main landing page, populate the main ("Overview") tab with content
- Misc UI improvements:
  - In the login flow, move the "Logout" and "Methods" buttons to be within the login frame
  - Set the visual login frame (box with rounded gray border) to be a more consistent height. Currently, progressions through the login and 2FA registration flows cause the visual login frame to change height on each step which is somewhat visually jarring for the user.

Items moved out from implementation follow-ups above:

- Webauthn UI improvements:
  - Implement device enable/disable
    - Frontend: https://github.com/authelia/authelia/pull/4436
- Flow updates:
  - Initial 2FA enrollment should lead user back to second-factor authentication instead of leaving them in the settings UI at the `OneFactor` authentication level
    - Idea: Introduce / use a value indicating the current user has a higher authentication level available than their current level

**Comment by james-d-elliott** [comment]
@all-contributors please add @smkent for code, design, and ideas

**Comment by smkent** [comment]
I'm working on adding a device name prompt to the WebAuthn registration flow. Here's a preview!

https://user-images.githubusercontent.com/2831985/201509253-f3cc467c-ff27-4200-a817-c0e6ae5ba0af.mp4

**Comment by smkent** [comment]
Much of the work for this is happening in https://github.com/authelia/authelia/pull/4376. Here's a preview of the current work in progress:


https://user-images.githubusercontent.com/2831985/202396548-ea751b16-29dd-4ead-8b6e-ee6db6aec3ab.mp4

**Comment by smkent** [comment]
Updated UI preview!

![more-preview](https://user-images.githubusercontent.com/2831985/204435705-ae37a2c6-8164-482a-94a0-78a388d9e43b.png)

**Comment by james-d-elliott** [comment]
@all-contributors please add @smkent for design

**Comment by archef2000** [comment]
When will [v4.38.0](https://www.authelia.com/roadmap/active/webauthn/#multi-device-registration) be released ?
